{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1720005890243, "stop": 1720005890465, "uuid": "3ced509f-0648-4f4e-a5cd-279fb0cbc623", "historyId": "d6150fd250f448eed742c8790c439484", "testCaseId": "d6150fd250f448eed742c8790c439484", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_nonexistent_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Ryzen-PC"}, {"name": "thread", "value": "15548-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}